flickr:
  lr: 0.001
  lr_f: 0.005
  num_hidden: 256
  num_heads: 2
  weight_decay: 2e-4
  weight_decay_f: 0
  max_epoch: 800
  max_epoch_f: 2500
  mask_rate: 0.50
  num_layers: 5
  encoder: gin
  decoder: gin
  activation: prelu
  in_drop: 0.2
  loss_fn: sce
  optimizer: adam
  alpha_l: 3
  norm: layernorm
  residual: True
  scheduler: True
  linear_prob: True

  missing_rate: 0.90
  mask_type: uniform
  filling_method: feature_propagation
  num_iterations: 40

  use_label_connect: True
  use_rec: True
  zero_fill: False
  train_edge_drop_rate: 0.15
  seeds: [0, 1, 2, 3, 4]

reddit:
  lr: 0.001
  lr_f: 0.005
  num_hidden: 512
  num_heads: 2
  weight_decay: 2e-4
  weight_decay_f: 0
  max_epoch: 300
  max_epoch_f: 3000
  mask_rate: 0.50
  num_layers: 4
  encoder: gin
  decoder: gin
  activation: prelu
  in_drop: 0.2
  loss_fn: sce
  optimizer: adam
  alpha_l: 3
  norm: layernorm
  residual: True
  scheduler: True
  linear_prob: True

  missing_rate: 0.90
  mask_type: uniform
  filling_method: feature_propagation
  num_iterations: 40

  use_label_connect: True
  use_rec: True
  zero_fill: False
  train_edge_drop_rate: 0.1
  seeds: [0, 1, 2, 3, 4]

sailing:
  lr: 0.001
  lr_f: 0.005
  num_hidden: 512
  num_heads: 2
  weight_decay: 2e-4
  weight_decay_f: 0
  max_epoch: 1200
  # 最优的是 1500，2000 会有下降
  max_epoch_f: 15000
  # 目测 25000 应该能收敛
  mask_rate: 0.75
  num_layers: 3
  encoder: gin
  decoder: gin
  activation: prelu
  in_drop: 0.2
  loss_fn: sce
  optimizer: adam
  alpha_l: 3
  norm: layernorm
  residual: True
  scheduler: True
  linear_prob: True

  missing_rate: 0.90
  mask_type: uniform
  filling_method: feature_propagation
  num_iterations: 40

  use_label_connect: True
  use_rec: True
  zero_fill: False
  train_edge_drop_rate: 0.1
  seeds: [0, 1, 2, 3, 4]